### PR TITLE
better serialization

### PR DESCRIPTION
**Pull request by joamatab**
- drop None from get_netlist. This avoids a lot of warnings in sax

@flaport

### CODE REVIEW

**Comment by thomaslima** [comment]
@joamatab @tvt173 Is this a permanent change? It messed with my tests - and I'd rather record the null arguments in the settings dictionary.

**Comment by tvt173** [comment]
hi @thomaslima , it seems to persist in gdsfactory8
https://github.com/gdsfactory/gdsfactory/blob/b652fde4b09203d3b0d92cada2809f14c3dd6e35/gdsfactory/get_netlist.py#L195

however, i'm not fully aware of the details on why this change was made, other than what is stated in this issue. we used to have an option in this function to let you toggle that behavior (record full settings vs. only non-default).
@joamatab @flaport what are your thoughts on this?

**Comment by joamatab** [comment]
this change is required when netlisting components that have references that are not registered in the PDK

I found 3 ways of fixing this:

- flatten imported GDS (slow and big sizes)
- extract full GDS subcells and register them in PDK (complex)
- Ignore those components from netlist extraction

We did a similar PR on gdsfactory8 recently

@nikosavola 
@sebastian-goeldi

**Comment by thomaslima** [comment]
Thanks everyone for the explanation. I have to say I don't understand the
reasons because I don't use sax (yet). But what does the netlist parameters
have to do with components not registered in PDK? Should I worry about that
too?

**Pull request merged**
